services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - ./scripts:/scripts  # Mount your SQL scripts directory
      - sql_data:/var/opt/mssql  # Mount volume for SQL Server data

volumes:
  sql_data:  